### ISSUE TITLE
Associate date/build information with the binary

### ISSUE THREAD

**Issue by machawk1** [ikreymer/webarchiveplayer#12]
I noticed when using this that there was no way to tell what version of the software I was using. It would be useful to know what version of the binary as well as other information (e.g., pywb version) the app uses.

On OS X, this information would normally be present in the "About" box. https://github.com/machawk1/wail/blob/osagnostic/bundledApps/WAIL.py#L232 and
https://github.com/machawk1/wail/blob/osagnostic/bundledApps/WAIL.py#L236-L246 are now I do it in WAIL for within-the-app.

From outside of the app, the version is also not evident.
![screen shot 2015-11-06 at 1 13 57 pm](https://cloud.githubusercontent.com/assets/2514780/11004799/52752c86-8488-11e5-9589-e7427d96ac2e.png)

This information is set in the app's .plist file in OS X. Pyinstaller does not have a way to specify a plist file on-build but recommends replacing it within the .app after the binary has been built. I do this in my MAKEFILE in WAIL:
https://github.com/machawk1/wail/blob/osagnostic/bundledApps/MAKEFILE.sh#L46
https://github.com/machawk1/wail/blob/osagnostic/build/Info.plist

It's not the ideal way, but it is a solution.

**Comment by ikreymer** [comment]
Thanks, added by manually modifying the generating Info.plist, though it seems the latest Pyinstaller 3.0 may have a way to specify the version explicitly..
