### ISSUE TITLE
File menu is empty

### ISSUE THREAD

**Issue by machawk1** [ikreymer/webarchiveplayer#13]
Clicking on the file menu shows no menu contents. A solution would be to completely get rid of the menu (I don't know if this is possible w/ wxPython). The "webarchiveplayer" menu should also contain a hook into an about box, per #12. OS X 10.11.1

![webarchiveplayer_nomenu](https://cloud.githubusercontent.com/assets/2514780/11005440/d420fec4-848b-11e5-98bf-f68b982540d2.gif)

**Comment by ikreymer** [comment]
Hm, this may be specific to OS X 10.11.1, there is actually a check in 1.2.0:

```
        if wx.Platform != "__WXMAC__":
            self.menu_bar.Append(self.help_menu, "File")
```

that supposed to add File menu only if not OS X for this reason...

Can you check if wx.Platform is returning something different for you?

**Comment by machawk1** [comment]
I re-downloaded the binary and sure enough, no file menu. The system-installation of wx should not matter unless built from source.
