### ISSUE TITLE
Files created using WARCreate don't work

### ISSUE THREAD

**Issue by lugusto** [ikreymer/webarchiveplayer#14]
I'm running Win7 SP1 Home. 

I'm using Chrome 46.0.2490.86 m with the latest version of http://warcreate.com/ extension to generate some .WARC files.

webarchiveplayer.exe 1.2.0 simply does nothing if I try to open any WARC file generated using that Chrome extension: no error message, no warning, nothing at all.

**Comment by ikreymer** [comment]
Do you have an example WARC that you could send?
I just tested, but on OS X, and was working fine.. Will try to test on Windows later

**Comment by lugusto** [comment]
[20151115231432337.warc.txt](https://github.com/ikreymer/webarchiveplayer/files/35077/20151115231432337.warc.txt)

I've renamed the file to .txt due to github not allowing .warc files

**Comment by ikreymer** [comment]
Thanks for submitting this. It looks like the metadata record of the WARC has an off by one error,
it is `Content-Length: 7397` but should actually be 7398, resulting an impartial read of the metadata record. As a result, WebArchivePlayer fails to index the WARC.
I've tested this with OpenWayback indexer, which will also fail to index this warc, and JWAT WARC tester, which will report errors in the warc. @machawk1 may want to know about this..

But, as far as WebArchivePlayer, it should still be able to index the WARC anyway despite the invalid content-length, and if not, should display a meaningful error message that the WARC is invalid. So a few things to fix...

**Comment by machawk1** [comment]
Thanks for the heads-up, @ikreymer. I'll test it out in the dev version of WARCreate.

**Comment by ikreymer** [comment]
The attached WARC will index and be usable in webarchiveplayer 1.3.0 (the truncated record was actually a metadata record at the end and so is not needed for replay)

**Comment by ikreymer** [comment]
Also added error dialog if a WARC can not be read, #18
