### ISSUE TITLE
Support for recent requests module

### ISSUE THREAD

**Issue by bzc6p** [ikreymer/webarchiveplayer#19]
I see webarchiveplayer needs `requests` version 2.5.1. Is there a chance it will support newer versions of it in the near future (or is it already possible, just the dependency record is not updated), or shall I set up a virtualenv not to have conflict with other applications? (Please consider this as a feature request.)

I don't know how complicated it would be, that's why I'm asking. Thanks for the reply.

**Comment by ikreymer** [comment]
The reason was that latter versions had problems with pyinstaller at the time, but it may have been fixed now.. will try.

**Comment by ikreymer** [comment]
Latest release works with latest requests.
