### ISSUE TITLE
Unable to select WARC files in Open dialog

### ISSUE THREAD

**Issue by machawk1** [ikreymer/webarchiveplayer#3]
I launch the app and am shown an Open dialog. I navigate to my WARCs but they are dimmed and not selectable.

OS X 10.10.2

Current binary (1.1.1?) from https://github.com/ikreymer/webarchiveplayer/blob/master/README.md .

![screen shot 2015-03-18 at 5 39 10 pm](https://cloud.githubusercontent.com/assets/2514780/6720069/e77bbb1a-cd95-11e4-97cf-1531e59b92f6.png)

**Comment by ikreymer** [comment]
Oops, yeah, I can confirm this for me as well.. forgot to check other extensions.. probably a typo in wx.FileDialog constructor.  Here's what it is currently (also had issues with .warc.gz / .arc.gz before):

```
wx.FileDialog(parent=self,
                               message='Please select a web archive (WARC or ARC) file',
                               #wildcard='(*.warc.gz*.arc.gz*.warc*.arc)|*.warc.gz*.arc.gz*.warc*.arc',
                               wildcard='WARC or ARC (*.gz; *.warc; *.arc)|*.gz; *.warc; *.arc',
                               style=style)
```

Hopefully just a typo here..

**Comment by ikreymer** [comment]
Yeah, just extra spacing.. (though still can't get it to accept _.warc.gz;_.arc.gz must do *.gz)
3adf10791c2982111e294f227e6472475c22ab13

(Updated the OS X binary)
