### ISSUE TITLE
Wrong dmg upload to the releases page?

### ISSUE THREAD

**Issue by vitorgalvao** [ikreymer/webarchiveplayer#30]
I just checked [the releases page](https://github.com/ikreymer/webarchiveplayer/releases) and the `dmg` and `exe` for the last two versions.

The `dmg` for versions `1.4.1` and `1.4.5` appear to be the exact same (same `sha256`). This suggests the one for the previous version was erroneously uploaded to the current one. `exe`s have different shasums so they seem to be correct.

**Comment by atomotic** [comment]
seems that the good dmg for 1.4.5 is this one: https://github.com/ikreymer/webarchiveplayer/blob/master/app/osx/webarchiveplayer.dmg

do you need the release for the brew formula, right?

**Comment by vitorgalvao** [comment]
Yes, we need it for the Homebrew-Cask cask (similar but not the same thing).

**Comment by ikreymer** [comment]
Sorry about that. We've just released a new version, 1.4.6, which should be up-to date on the release page. You should use this version if possible. If you still need the 1.4.5 version, let me know.

**Comment by vitorgalvao** [comment]
No need for `1.4.5`. `1.4.6` will work fine. Thank you.
