### ISSUE TITLE
Fails to run on docker

### ISSUE THREAD

**Issue by dportabella** [ikreymer/webarchiveplayer#35]
$ docker run -ti python bash

$ git clone https://github.com/ikreymer/webarchiveplayer

$ cd webarchiveplayer

$ python setup.py install
running install
running bdist_egg
running egg_info
writing webarchiveplayer.egg-info/PKG-INFO
writing dependency_links to webarchiveplayer.egg-info/dependency_links.txt
writing entry points to webarchiveplayer.egg-info/entry_points.txt
writing requirements to webarchiveplayer.egg-info/requires.txt
writing top-level names to webarchiveplayer.egg-info/top_level.txt
reading manifest file 'webarchiveplayer.egg-info/SOURCES.txt'
writing manifest file 'webarchiveplayer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/archiveplayer
copying build/lib/archiveplayer/version.py -> build/bdist.linux-x86_64/egg/archiveplayer
copying build/lib/archiveplayer/__init__.py -> build/bdist.linux-x86_64/egg/archiveplayer
copying build/lib/archiveplayer/archiveplayer.py -> build/bdist.linux-x86_64/egg/archiveplayer
copying build/lib/archiveplayer/pagedetect.py -> build/bdist.linux-x86_64/egg/archiveplayer
creating build/bdist.linux-x86_64/egg/archiveplayer/templates
copying build/lib/archiveplayer/templates/index.html -> build/bdist.linux-x86_64/egg/archiveplayer/templates
copying build/lib/archiveplayer/templates/pagelist_search.html -> build/bdist.linux-x86_64/egg/archiveplayer/templates
byte-compiling build/bdist.linux-x86_64/egg/archiveplayer/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/archiveplayer/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/archiveplayer/archiveplayer.py to archiveplayer.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/archiveplayer/pagedetect.py to pagedetect.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying webarchiveplayer.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/webarchiveplayer-1.4.7-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing webarchiveplayer-1.4.7-py3.6.egg
Removing /usr/local/lib/python3.6/site-packages/webarchiveplayer-1.4.7-py3.6.egg
Copying webarchiveplayer-1.4.7-py3.6.egg to /usr/local/lib/python3.6/site-packages
webarchiveplayer 1.4.7 is already the active version in easy-install.pth
Installing webarchiveplayer script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/webarchiveplayer-1.4.7-py3.6.egg
Processing dependencies for webarchiveplayer==1.4.7
Searching for requests==2.18.4
Best match: requests 2.18.4
Processing requests-2.18.4-py3.6.egg
requests 2.18.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg
Searching for waitress==1.1.0
Best match: waitress 1.1.0
Processing waitress-1.1.0-py3.6.egg
waitress 1.1.0 is already the active version in easy-install.pth
Installing waitress-serve script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/waitress-1.1.0-py3.6.egg
Searching for pywb==2.0.1
Best match: pywb 2.0.1
Processing pywb-2.0.1-py3.6.egg
pywb 2.0.1 is already the active version in easy-install.pth
Installing pywb script to /usr/local/bin
Installing wayback script to /usr/local/bin
Installing cdx-server script to /usr/local/bin
Installing live-rewrite-server script to /usr/local/bin
Installing cdx-indexer script to /usr/local/bin
Installing wb-manager script to /usr/local/bin
Installing warcserver script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/pywb-2.0.1-py3.6.egg
Searching for urllib3==1.22
Best match: urllib3 1.22
Processing urllib3-1.22-py3.6.egg
urllib3 1.22 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg
Searching for idna==2.6
Best match: idna 2.6
Processing idna-2.6-py3.6.egg
idna 2.6 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/idna-2.6-py3.6.egg
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Processing chardet-3.0.4-py3.6.egg
chardet 3.0.4 is already the active version in easy-install.pth
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/chardet-3.0.4-py3.6.egg
Searching for certifi==2018.1.18
Best match: certifi 2018.1.18
Processing certifi-2018.1.18-py3.6.egg
certifi 2018.1.18 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/certifi-2018.1.18-py3.6.egg
Searching for wsgiprox==1.4.1
Best match: wsgiprox 1.4.1
Processing wsgiprox-1.4.1-py3.6.egg
wsgiprox 1.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/wsgiprox-1.4.1-py3.6.egg
Searching for Werkzeug==0.14.1
Best match: Werkzeug 0.14.1
Processing Werkzeug-0.14.1-py3.6.egg
Werkzeug 0.14.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/Werkzeug-0.14.1-py3.6.egg
Searching for webencodings==0.5.1
Best match: webencodings 0.5.1
Processing webencodings-0.5.1-py3.6.egg
webencodings 0.5.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/webencodings-0.5.1-py3.6.egg
Searching for webassets==0.12.1
Best match: webassets 0.12.1
Processing webassets-0.12.1-py3.6.egg
webassets 0.12.1 is already the active version in easy-install.pth
Installing webassets script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/webassets-0.12.1-py3.6.egg
Searching for warcio==1.5.1
Best match: warcio 1.5.1
Processing warcio-1.5.1-py3.6.egg
warcio 1.5.1 is already the active version in easy-install.pth
Installing warcio script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/warcio-1.5.1-py3.6.egg
Searching for surt==0.3.0
Best match: surt 0.3.0
Processing surt-0.3.0-py3.6.egg
surt 0.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/surt-0.3.0-py3.6.egg
Searching for six==1.11.0
Best match: six 1.11.0
Processing six-1.11.0-py3.6.egg
six 1.11.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/six-1.11.0-py3.6.egg
Searching for redis==2.10.6
Best match: redis 2.10.6
Processing redis-2.10.6-py3.6.egg
redis 2.10.6 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Processing PyYAML-3.12-py3.6-linux-x86_64.egg
PyYAML 3.12 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/PyYAML-3.12-py3.6-linux-x86_64.egg
Searching for portalocker==1.1.0
Best match: portalocker 1.1.0
Processing portalocker-1.1.0-py3.6.egg
portalocker 1.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/portalocker-1.1.0-py3.6.egg
Searching for Jinja2==2.8.1
Best match: Jinja2 2.8.1
Processing Jinja2-2.8.1-py3.6.egg
Jinja2 2.8.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/Jinja2-2.8.1-py3.6.egg
Searching for gevent==1.2.2
Best match: gevent 1.2.2
Processing gevent-1.2.2-py3.6-linux-x86_64.egg
gevent 1.2.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/gevent-1.2.2-py3.6-linux-x86_64.egg
Searching for brotlipy==0.7.0
Best match: brotlipy 0.7.0
Processing brotlipy-0.7.0-py3.6-linux-x86_64.egg
brotlipy 0.7.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/brotlipy-0.7.0-py3.6-linux-x86_64.egg
Searching for certauth==1.2
Best match: certauth 1.2
Processing certauth-1.2-py3.6.egg
certauth 1.2 is already the active version in easy-install.pth
Installing certauth script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/certauth-1.2-py3.6.egg
Searching for tldextract==2.2.0
Best match: tldextract 2.2.0
Processing tldextract-2.2.0-py3.6.egg
tldextract 2.2.0 is already the active version in easy-install.pth
Installing tldextract script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages/tldextract-2.2.0-py3.6.egg
Searching for MarkupSafe==1.0
Best match: MarkupSafe 1.0
Processing MarkupSafe-1.0-py3.6-linux-x86_64.egg
MarkupSafe 1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/MarkupSafe-1.0-py3.6-linux-x86_64.egg
Searching for greenlet==0.4.13
Best match: greenlet 0.4.13
Processing greenlet-0.4.13-py3.6-linux-x86_64.egg
greenlet 0.4.13 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/greenlet-0.4.13-py3.6-linux-x86_64.egg
Searching for cffi==1.11.4
Best match: cffi 1.11.4
Processing cffi-1.11.4-py3.6-linux-x86_64.egg
cffi 1.11.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/cffi-1.11.4-py3.6-linux-x86_64.egg
Searching for pyOpenSSL==17.5.0
Best match: pyOpenSSL 17.5.0
Processing pyOpenSSL-17.5.0-py3.6.egg
pyOpenSSL 17.5.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/pyOpenSSL-17.5.0-py3.6.egg
Searching for setuptools==38.5.1
Best match: setuptools 38.5.1
Adding setuptools 38.5.1 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-3.6 script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages
Searching for requests-file==1.4.3
Best match: requests-file 1.4.3
Processing requests_file-1.4.3-py3.6.egg
requests-file 1.4.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/requests_file-1.4.3-py3.6.egg
Searching for pycparser==2.18
Best match: pycparser 2.18
Processing pycparser-2.18-py3.6.egg
pycparser 2.18 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/pycparser-2.18-py3.6.egg
Searching for cryptography==2.1.4
Best match: cryptography 2.1.4
Processing cryptography-2.1.4-py3.6-linux-x86_64.egg
cryptography 2.1.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/cryptography-2.1.4-py3.6-linux-x86_64.egg
Searching for asn1crypto==0.24.0
Best match: asn1crypto 0.24.0
Processing asn1crypto-0.24.0-py3.6.egg
asn1crypto 0.24.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/site-packages/asn1crypto-0.24.0-py3.6.egg
Finished processing dependencies for webarchiveplayer==1.4.7

$ webarchiveplayer
Traceback (most recent call last):
  File "/usr/local/bin/webarchiveplayer", line 11, in <module>
    load_entry_point('webarchiveplayer==1.4.7', 'console_scripts', 'webarchiveplayer')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/webarchiveplayer-1.4.7-py3.6.egg/archiveplayer/archiveplayer.py", line 3, in <module>
ModuleNotFoundError: No module named 'pywb.framework'

**Comment by ikreymer** [comment]
Same issue as #34, this project is not being maintained anymore. The exact issue is that this requires an older version of pywb to work. But, pywb 2.0.x ships with a Dockerfile that you can use directly as well. (More docs probably needed there).
