### ISSUE TITLE
Unable to launch 1.1.2 on OS X

### ISSUE THREAD

**Issue by machawk1** [ikreymer/webarchiveplayer#5]
Using version 1.1.1 binary on OS X 10.10.2. The .app show the icon in the dock then immediately quits. I built from source using the shell script and ran the webarchiveplayer in the dist folder that accompanies the .app. This produced the following error on the command-line, which might be the culprit.

``` sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named archiveplayer.archiveplayer
```

**Comment by ikreymer** [comment]
Hmm, I haven't tested on 10.10 yet...

Can you provide more details about your setup? What version of python? 2.7.9?
And this was after running `build-osx.sh`, right?

**Comment by ikreymer** [comment]
Oh, it occured to me that the readme is missing `python setup.py install` .. did you run that when you got the error? Will fix that now to make it clear.

**Comment by machawk1** [comment]
I should have been more specific. I was attempting to build by launching `./app/build-osx.sh` and not running setup.py.

Given my delay in response, I just cloned a fresh copy of the repo.

When I run `python setup.py install` then run the `webarchiveplayer` command, I am shown an icon in the pyinstaller application icon (rocket + python logo) and the OS X "Open" window, as expected.

Same machine. I download the .dmg from the "Download for OS X" link in README.md. I double-click the pyinstaller binary icon (a floppy disk with a yellow python). No icon is shown in the OS X dock and no Open window open.

Is the binary in the .dmg current relative to the source?

Are you using the pyinstaller `--windowed` flag when building the .app?

Python 2.7.6, OS X 10.10.2

**Comment by ikreymer** [comment]
I bet it has something to do with wxPython. If you were building in a virtualenv, you need to symlink wxpython to the virtualenv (updated the README with more details).

I just pushed a new 1.1.2 release, hopefully this will work for you:
https://github.com/ikreymer/webarchiveplayer/releases/tag/1.1.2

**Comment by machawk1** [comment]
@ikreymer I just tried this again using your version 1.1.2 binary at https://github.com/ikreymer/webarchiveplayer . OS X 10.10.3, Python 2.7.6. When I launch the .app from the mounted disk image, I get an error message saying the file is damaged. I also tried first dragging the .app to the /Applications folder and get a similar result.

![screen shot 2015-05-14 at 10 30 15 am](https://cloud.githubusercontent.com/assets/2514780/7633794/95204bc2-fa24-11e4-89ea-865fb72c2350.png)

![screen shot 2015-05-14 at 10 30 10 am](https://cloud.githubusercontent.com/assets/2514780/7633820/e3849b92-fa24-11e4-85c9-1b4e85121e17.png)

![screen shot 2015-05-14 at 10 32 09 am](https://cloud.githubusercontent.com/assets/2514780/7633797/a88967c0-fa24-11e4-8537-1db4e1dd5563.png)

**Comment by ikreymer** [comment]
I don't have Yosemite but will try to find a way to test this.. It seems like it could be related to security (webarchiveplayer is not signed).. https://www.my-private-network.co.uk/knowledge-base/apple-related-questions/osx-unsigned-apps.html Can you check your security settings?

**Comment by machawk1** [comment]
That was precisely the issue. Once I selected, "allow from anywhere", I was able to load a WARC for replay. Screenshots of process:

![1locked](https://cloud.githubusercontent.com/assets/2514780/7635665/3b69e794-fa30-11e4-844c-4bb10487f4c5.png)
![2auth](https://cloud.githubusercontent.com/assets/2514780/7635666/3db4c9ba-fa30-11e4-9f25-c5c475326e9e.png)
![3choose](https://cloud.githubusercontent.com/assets/2514780/7635670/412cdf42-fa30-11e4-870b-ad29af6b23c5.png)
![4allow](https://cloud.githubusercontent.com/assets/2514780/7635672/43973e26-fa30-11e4-8447-59333492b3fd.png)
