### ISSUE TITLE
Excessive memory usage when serving big files

### ISSUE THREAD

**Issue by bzc6p** [ikreymer/webarchiveplayer#6]
On Debian 7, I loaded a WARC that contained some larger files (200-300 MB). The loading went smoothly, but when I tried to access the file in a browser (in this case, Firefox), memory usage of the process pywb (or python? or webarchiveplayer? can't remember and I can't test it again now) increased up to 700-800 MB when I ran out of memory and the following error messages appeared in the terminal:

```
Pywb Error

Error Details:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/framework/wsgi_wrappers.py", line 98, in handle_methods
    response = wb_router(env)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/framework/archivalrouter.py", line 39, in __call__
    return route.handler(wbrequest)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/handlers.py", line 73, in __call__
    return self.handle_request(wbrequest)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/handlers.py", line 141, in handle_request
    return self.handle_replay(wbrequest, cdx_lines)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/handlers.py", line 155, in handle_replay
    cdx_callback)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/replay_views.py", line 90, in render_content
    failed_files)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/replay_views.py", line 123, in cached_replay_capture
    return get_capture()
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/replay_views.py", line 115, in get_capture
    failed_files)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/replay_views.py", line 183, in replay_capture
    response_iter)
  File "/usr/local/lib/python2.7/dist-packages/pywb-0.8.3-py2.7.egg/pywb/webapp/replay_views.py", line 205, in buffered_response
    content = out.getvalue()
MemoryError
```

Interestingly, when I accessed the file via wget (initiated a download), it was able to serve, however, there was some strain there too. (I haven't checked the memory usage, though.)

I guess the problem is easily reproducible: you can find the WARC here: https://archive.org/details/hajduvolan_hu_2015_05, and the largest file (an flv video) is on this page: http://hajduvolan.hu/2011-2012-475.html, you'll find it in an embedded player, or you can directly download it with the link under the player.

I believe it's not a problem with the browser, but some bug in pywb. (I wondered if I should file this issue to pywb, but that's a newer version than the one utilized by webarchiveplayer. Maybe the problem has been fixed since?) And I believe 700 MB of memory usage is too much for a 250 MB file.

In case if it's not a bug with webarchiveplayer or pywb, or if the problem has been fixed sine, I apologize for this issue. Also sorry for me not being able to do more tests on it.

**Comment by ikreymer** [comment]
Hi, thanks for the report, I will test it with the latest pywb and with webarchiveplayer (it needs to be upgraded to latest pywb, just haven't had the chance).

Yes, it should certainly not use that much memory, perhaps it is buffering the video instead of streaming it somehow.

**Comment by ikreymer** [comment]
@bzc6p I just released an update to pywb, which fixes this issue.. Will update webarchiveplayer also when I have more time.

Also, while working on this, I made a new project which lets you connect to an IA item directly:
https://github.com/ikreymer/pywb-ia

If you run that project, you can then load in your browser directly:
`http://localhost:8080/item/hajduvolan_hu_2015_05/http://hajduvolan.hu/2011-2012-475.html`

This will stream everything form the item and you don't even need to download the WARC locally. The video should work correctly also.

**Comment by ikreymer** [comment]
Just released latest WebArchivePlayer which uses the latest pywb, so this is now fixed in WebArchivePlayer.

**Comment by wjs68** [comment]
Hi, whilst I see a definite improvement in 1.1.3 of webarchiveplayer with speed and with displaying 'some' pages properly, it no longer shows full html code when using "view source" in either chrome or firefox. Hopefully it can be fixed in the next version. 

You can compare both versions with this example warc: http://warctozip.archive.org/2103984777-2115399424/webshots.com-user-chicagonights-20121019-053550.warc.gz/http://archive.org/download/webshots-freeze-frame-20121019053616/webshots-20121019053616.megawarc.warc.gz

Great piece of software by the way for casual users like myself who are not so into the technical side of things. Thanks for your work.

**Comment by ikreymer** [comment]
@wjs68 WebArchivePlayer is displaying the content in a frame, while the outer frame contains the banner. I could add an option to not use the frame at all. To see the source of the content, you can selected "View Frame Source" in chrome and in FF, selected "This Frame -> View Frame Source"

If you see some pages that don't display properly, feel free to open a separate issue for those as well.

**Comment by wjs68** [comment]
Thanks ikreymer, that works fine for me and I'm happy enough with that solution. I'll continue testing on other warc sources and let you know if there's any issues.
