### ISSUE TITLE
Issue building GUI binaries on OS X

### ISSUE THREAD

**Issue by machawk1** [ikreymer/webarchiveplayer#9]
I was attempting to build the GUI binary for OS X 10.10.5 and ran into some issues using the following commands:
1. `git clone https://github.com/ikreymer/webarchiveplayer` 
2. `cd webarchiveplayer/app`
3. `./build-osx.sh`
   - `webarchiveplayer/app/osx/webarchiveplayer.dmg` is created as well as the pre-packaged products at `webarchiveplayer/app/dist/{webarchiveplayer,webarchiveplayer.app}`. 
4. I open the .dmg to reveal a file/directory named `webarchiveplayer.app`.
5. I launch the app via double-click. It immediately closes (the icon is shown and hidden quickly in the dock).
   - The `webarchiveplayer/app/dist/webarchiveplayer.app` file exhibits the same behavior.
6. Per the procedure I have used to remedy this behavior in WAIL, I launched the `webarchiveplayer/app/dist/webarchiveplayer` file and receive the error:
   - `Traceback (most recent call last):
     File "<string>", line 1, in <module>
     ImportError: No module named archiveplayer.archiveplayer`

I played devil's advocate and tried `pip install archiveplayer` to no avail (the package is not in pip).

I then ran the system-wide installation via `python setup.py install` and re-ran `./build-osx.sh`, which produced another .dmg (I was sure to remove the original .dmg and build remnants).

I relaunched the `.app` in the `.dmg` and the Open window now displays as expected. This indicates to me that the `python setup install.py` must be run before the GUI can be built. I have not tested whether  the binary is reliant on the system-installed package when using the pyinstaller-interfacing build script you have provided. It might be useful to provide a requirements file and amend the instructions to first install the dependencies for pyinstaller to access and include in the binary.

I realize that this is a derivative project of pywb but there is definitely appeal in provide a native simple interface to replaying WARCs as you have here. I also hope to extensively reuse your code when I can find the time.

**Comment by ikreymer** [comment]
I'm not sure this is an issue, the instructions state that `python setup.py install` should be run as part of the installation after cloning...

**Comment by ikreymer** [comment]
You can also run `python setup.py install` in a virtualenv, but then you also need to symlink the wx library to that virtualenv
